version: "3.8"
services:
  postgres:
    image: postgres:16-alpine
    container_name: ilmercatinodellibro-postgres
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres:/var/lib/postgres/data
    networks:
      - postgres
    # https://github.com/docker-library/docs/blob/master/postgres/README.md#environment-variables
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
  redis:
    image: "redis:alpine"
    container_name: ilmercatinodellibro-redis
    ports:
      - "${QUEUE_PORT:-6379}:6379"

volumes:
  postgres:

networks:
  postgres:
    driver: bridge
