name: il-mercatino-del-libro
services:
  postgres:
    image: postgres:16-alpine
    container_name: ilmercatinodellibro-postgres
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres:/var/lib/postgres/data
      - ${STORAGE_PATH}/tmp:/tmp/tmp-files
    # https://github.com/docker-library/docs/blob/master/postgres/README.md#environment-variables
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}

  backup:
    image: alpine:latest
    container_name: backup
    depends_on:
      - postgres
    volumes:
      - ../../:/app:ro
      - ./backup/scripts:/scripts
      - ${HOME}/mdl_backups/logs:/logs
      - ${HOME}/mdl_backups/backups:/backups
      - ./backup/config/crontabs:/etc/crontabs/root
      - ./backup/config/msmtprc:/etc/msmtprc_template
      - ./backup/config/rclone.conf:/root/.config/rclone/rclone.conf_template
    env_file:
      - .env
    command: >
      sh -c '
      apk add --no-cache rclone postgresql-client tzdata msmtp gettext &&
      envsubst < /etc/msmtprc_template > /etc/msmtprc && chmod 600 /etc/msmtprc &&
      envsubst < /root/.config/rclone/rclone.conf_template > /root/.config/rclone/rclone.conf && 
      chmod +x /scripts/*.sh && chmod 600 /root/.config/rclone/rclone.conf &&
      crond -f
      '

volumes:
  postgres:

networks:
  default:
    name: mercatino_network
