export enum AvailableRouteNames {
  Catalog = "catalog",
  Contacts = "contacts",
  Events = "events",
  Theme = "theme",
  ResetPassword = "reset-password",
  ForgotPassword = "forgot-password",
  ChangePassword = "change-password",
  RolesAndPermissions = "roles-and-permissions",
  RegisterWithToken = "invite",
  Login = "login",
  UsersManagement = "users-management",
  SalableBooks = "salable-books",
  MyBooks = "my-books",
  ReserveBooks = "reserve-books",
  WhoWeAre = "who-we-are",
  JoinUs = "join-us",
}
